site_name: SAMOSA Supramolecular Explorer
site_description: "Self-Assembly of Metal-Organic Supramolecular Architectures"
site_author: "Filip T. Szczypiński"
site_url: "https://fiszczyp.github.io/supramol_explorer"
repo_url: "https://github.com/fiszczyp/supramol_explorer"
repo_name: "fiszczyp/supramol_explorer"
site_dir: "site"
copyright: Copyright &copy; 2024 Filip Szczypiński
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Database Schema: database.md

theme:
  name: "material"
  logo: img/samosa.svg
  favicon: img/samosa.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true

          docstring_options:
            ignore_init_summary: true

markdown_extensions:
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/fiszczyp.bsky.social
